### ISSUE TITLE
Improve accessibility of results table

### ISSUE THREAD

**Issue by dwhieb** [dwhieb/Nisinoon#133]
- [x] Wrap in `<div aria-labelledby=results-caption role=region tabindex=0>`
- [x] Add table caption: `<caption class=visually-hidden id=results-caption>` + `<h2>` inside of it.
- [x] Add `scope=col` to `<th>` elements.
- [x] Indicate scrollability.

```css
/* Scrolling Visual Cue */
/* https://lea.verou.me/blog/2012/04/background-attachment-local/ */

.table-wrapper {
  background: linear-gradient(to right, #fff 30%, rgba(255, 255, 255, 0)),
    linear-gradient(to right, rgba(255, 255, 255, 0), #fff 70%) 0 100%,
    radial-gradient(
      farthest-side at 0% 50%,
      rgba(0, 0, 0, 0.2),
      rgba(0, 0, 0, 0)
    ),
    radial-gradient(
        farthest-side at 100% 50%,
        rgba(0, 0, 0, 0.2),
        rgba(0, 0, 0, 0)
      )
      0 100%;
  background-repeat: no-repeat;
  background-color: #fff;
  background-size: 40px 100%, 40px 100%, 14px 100%, 14px 100%;
  background-position: 0 0, 100%, 0 0, 100%;
  background-attachment: local, local, scroll, scroll;
}
```
